name: hero_squad
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.1.0+1
  easy_debounce: 2.0.1
  font_awesome_flutter: 8.11.0
  google_fonts: 2.1.0
  intl: 0.17.0
  json_path: 0.2.1
  page_transition: 2.0.4
  photo_view: ^0.13.0
  shared_preferences: 2.0.11
  timeago: 3.1.0
  url_launcher: 6.0.15
  multi_select_flutter: ^4.1.2
  cupertino_icons: ^1.0.0
  reactive_forms: ^10.3.0
  http: ^0.13.4

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
